config/routes.rb
Rails.application.routes.draw do
  resources :works
  resources :tags
  resources :posts

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'posts#index'

  get 'blog-archive' => 'posts#archive'
  get 'feed'         => 'posts#feed'
  get 'about'        => 'about#index'

end

app/models/work.rb
class Work < ActiveRecord::Base
  validates_presence_of :name, :cover_image_url, :description

  paginates_per 15
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  require "#{Rails.root}/lib/contentManager.rb"

  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.not_deleted.page params[:page]
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work_contents = ContentURLsManager.json_content_urls(@work.content_urls)
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(
          :name,
          :cover_image_url,
          :description,
          :date,
          :role,
          :work_type,
          :content_urls)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
    <% if @work.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

        <ul>
        <% @work.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label "Project Name:" %>
    <%= f.text_field :name %>

    <%= f.label "Cover Image URL:" %>
    <%= f.text_field :cover_image_url %>

    <%= f.label "Date of Project:" %>
    <%= f.date_field :date %>

    <%= f.label "Role:" %>
    <%= f.text_field :role %>

    <%= f.label "Project Type:" %>
    <%= f.text_field :work_type %>

    <%= f.label "Description:" %>
    <%= f.text_area :description, size: "12x20" %>

    <%= f.label "Content URLs:" %>
    <%= f.text_area :content_urls, size: "12x20" %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/works/edit.html.erb
<div class="row first-row">
  <div class="small-12 medium-12 large-12 small-centered columns">
    <h1>Edit Project</h1>

    <p>
      <%= link_to("← All Projects", works_path) %> | <%= link_to 'Show Project', work_path(@work.id) %>
    </p>

    <%= render 'form' %>
  </div>
</div>

app/views/works/index.html.erb
<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <% if user_signed_in? %>
        <p>
          <%= link_to 'New Work', new_work_path %>
        </p>
    <% end %>

    <% if @works.empty? %>
        <h4 class="no-works-message">There are no projects yet... Stay tuned</h4>
    <% end %>

    <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-3 inline-list-custom">

      <% @works.each do |work| %>
          <!-- Begin project -->
          <li>
            <div class="thumbnail">
              <div class="thumbnail-img">
                <div class="thumbnail-hover">
                  <%= link_to("", work_path(work.id)) %>
                </div>
                <%= link_to image_tag(work.cover_image_url, alt: work.name), work_path(work.id) %>
              </div>
              <div class="thumbnail-caption">
                <%= link_to(work.name.capitalize, work_path(work.id), class: "caption-link" ) %>
              </div>
            </div>
          </li>
          <!-- End project -->
      <% end %>

    </ul>

    <%= paginate @works %>
  </div>
</div>

app/views/works/new.html.erb
<div class="row first-row">
  <div class="small-12 medium-12 large-12 small-centered columns">
    <h1>New Project</h1>

    <p>
      <%= link_to("← All Projects", works_path) %>
    </p>

    <%= render 'form' %>
  </div>
</div>

app/views/works/show.html.erb
<div class="row">
  <p>
    <%= link_to("← All Projects", works_path) %>
    <% if user_signed_in? %>
        | <%= link_to 'Edit Project', edit_work_path(@work) %>
    <% end %>
  </p>
  <div class="small-12 medium-7 large-7 columns">
    <h2><%= @work.name %></h2>
    <p>
      <%= @work.description %>
    </p>
  </div>
  <div class="small-12 medium-5 large-5 columns">
    <div class="lined-list">
      <ul>
        <li>
          <strong>Role:</strong>
          <% if @work.role.present? %>
              <%= @work.role.capitalize %>
          <% end %>
        </li>
        <li>
          <strong>Project Type:</strong>
          <% if @work.work_type.present? %>
              <%= @work.work_type.capitalize %>
          <% end %>
        </li>
        <li>
          <strong>Month & Year:</strong>
          <% if @work.date.present? %>
              <%= @work.date.strftime("%B %Y") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <hr class="project-detail-hr" />

    <% @work_contents.each do |content| %>
        <!-- Begin project image -->
        <div class="project-img">
          <iframe src="<%= content[:url] %>" width="100%" height="480"></iframe>
          <h6><%= content[:caption] %></h6>
        </div>
        <!-- End project image -->
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-12 large-12 columns">
    <p class="back-to-top-holder"><a class="back-to-top"><i class="fa fa-chevron-circle-up fa-3x"></i></a></p>
  </div>
</div>