config/routes.rb
Rails.application.routes.draw do
  resources :works
  resources :tags
  resources :posts

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  root 'posts#index'

  get 'blog-archive' => 'posts#archive'
  get 'feed'         => 'posts#feed'
  get 'about'        => 'about#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  # config for friendly_id gem --> use :title instead of :id in urls
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author, class_name: 'User'

  has_and_belongs_to_many :tags

  validates_presence_of :title

  def get_tag_list
    self.tags.map(&:id).map(&:to_s)
  end

  def creation_year
    self.created_at.year
  end

  def self.by_creation_year(year)
    where('extract(year from created_at) = ?', year)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.not_deleted.order("created_at DESC").page params[:page]
    @tags = Tag.not_deleted
  end

  # GET /posts/archive
  def archive
    @grouped_posts = group_post(Post.not_deleted.order("created_at DESC"))
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.tags = Tag.where(id: check_tags(params[:post][:tags]))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.tags = Tag.where(id: check_tags(params[:post][:tags]))
        @post.save!
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /feed
  def feed
    @posts = Post.not_deleted.order("created_at DESC")
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :slug)
    end

    # Verifies if there are new tags in the submitted parameters.
    # If so, creates the new tags and correctly formats the tag_list with the new tags
    def check_tags(tag_list)
      tag_list.reject!(&:empty?)

      tag_list.each_with_index do |tag_value, index|
        if tag_value.to_i == 0 # If it's a word, not an id
          new_tag_id = Tag.create(name: tag_value).id
          tag_list[index] = new_tag_id.to_s
        end
      end
    end

    # Groups all posts in a structure like:
    # { year => { "month" => { posts } } }
    def group_post(posts)
      grouped_posts = {}
      all_years = posts.map(&:creation_year).uniq

      all_years.each do |year|
        grouped_posts[year] = Post.by_creation_year(year).group_by { |post| post.created_at.strftime("%B") }
      end

      return grouped_posts
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

  /**
   *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
   */

   var disqus_config = function () {
   this.page.url = '<%= url_for([@post, {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
   this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
   this.page.title = '<%= @post.title %>';
   };

  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//francesca-blogfolio.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label "Title:" %>
    <%= f.text_field :title %>

    <%= f.label "Tags:" %>
    <%= f.select(
            :tags,
            options_from_collection_for_select(
                Tag.not_deleted,
                "id",
                "name",
                @post.get_tag_list,
            ),
            {},
            multiple: true,
            class: "selectize-control multi plugin-remove_button"
        ) %>

    <%= f.label "Body:" %>
    <% if @post.body.nil? %>
        <%= f.text_area :body, size: "12x60", escape: false, :value => "<p></p>" %>
    <% else %>
        <%= f.text_area :body, size: "12x60", escape: false%>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/archive.html.erb
<div>
  <div class="row first-row">
    <div class="small-12 small-centered medium-8 large-8 columns">
      <p>
        <%= link_to("← All Posts", posts_path) %>
      </p>
      <h1 class="archive-title">Blog Archive</h1>

      <div class="archive-item">
        <% @grouped_posts.each do |year, posts_by_month| %>
            <h4><%= year %></h4>
            <div>
              <% posts_by_month.each do |month, posts| %>
                  <div>
                    <h5><%= month %></h5>
                    <div>
                      <ul>
                        <% posts.each do |post| %>
                            <li><%= link_to(post.title.capitalize, post_path(post.id)) %></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="row first-row">
  <div class="small-12 medium-12 large-12 small-centered columns">
    <h1>Edit Post</h1>

    <p>
      <%= link_to("← All Posts", posts_path) %> | <%= link_to 'Show Post', @post %>
    </p>

    <%= render 'form' %>

  </div>
</div>

app/views/posts/index.html.erb
<div>
  <div class="row first-row">
    <div class=" large-8 medium-push-4 medium-8 columns ">
      <% if @posts.empty? %>
          <h4 class="no-posts-message">There are no posts yet... Stay tuned</h4>
      <% end %>

      <% @posts.each do |post| %>
          <article>
            <h1>
              <%= link_to(post.title.capitalize, post)%>
            </h1>
            <h6 class="date">
              <%= post.created_at.strftime("%B %d, %Y") %>
              <% if post.tags.any? %>
                  |
                  <% post.tags.each do |post_tag| %>
                      #<%= link_to(post_tag.name.downcase, post_tag) %>
                  <% end %>
              <% end %>
            </h6>
            <p>
              <!--Display 20% of the post body-->
              <%= post.body[0..post.body.length*20/100].html_safe %>
            </p>
            <p>
              <%= link_to("Continue reading →", post) %>
            </p>
          </article>
      <% end %>
      <%= paginate @posts %>
    </div>

    <div class="large-4 medium-4 medium-pull-8 columns">
      <aside class="blog-sidebar">
        <% if user_signed_in? %>
            <p>
              <%= link_to 'New Post', new_post_path %>
            </p>
        <% end %>
        <h5>Tags:</h5>
        <ul>
          <% @tags.each do |tag| %>
              <li>
                <%= link_to(tag.name.capitalize, tag) %>
              </li>
          <% end %>
        </ul>
        <p>
          <%= link_to("Blog Archive", blog_archive_path) %>
        </p>
        <p>
          <%= link_to ' Subscribe', "http://www.francesca.ga/feed.rss", target: "_blank", class: "fa fa-rss-square" %>
        </p>
      </aside>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row first-row">
  <div class="small-12 medium-12 large-12 small-centered columns">
    <h1>New Post</h1>

    <p>
      <%= link_to("← All Posts", posts_path) %>
    </p>

    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <div class="row first-row">
    <div class="small-12 medium-9 large-8 columns small-centered">
      <p>
        <%= link_to("← All Posts", root_path) %>
        <% if user_signed_in? %>
            | <%= link_to 'Edit Post', edit_post_path(@post) %>
        <% end %>
      </p>
      <article class="show_post_article">
        <h1>
          <%= @post.title.capitalize %>
        </h1>
        <h6 class="date">
          <%= @post.created_at.strftime("%B %d, %Y") %>
          <% if @post.tags.any? %>
              |
              <% @post.tags.each do |post_tag| %>
                  #<%= link_to(post_tag.name.downcase, post_tag) %>
              <% end %>
          <% end %>
        </h6>

        <div>
          <%= @post.body.html_safe %>
        </div>
        <p class="byline">
          Author:
          <% if @post.author %>
              <%= link_to(@post.author.username.capitalize, about_path, rel: "author") %>
          <% end %>
        </p>

        <div class="social-inline">
          <h5>Share this post:</h5>
          <a class="fa fa-twitter fa-2x"
             onclick="window.open('https://twitter.com/intent/tweet?text=<%= @post.title %> by @Mandarina_P - &amp;url=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left= 300'); void(0);">
          </a>
          <a class="fa fa-facebook fa-2x"
             onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left= 300'); void(0);">
          </a>
          <a class="fa fa-google-plus fa-2x"
             onclick="window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}])%>', '_blank', 'width=800, height=500, top=200, left= 300'); void(0);">
          </a>
        </div>
      </article>

      <div class="comments">

        <%= render 'disqus' %>

      </div>

    </div>
  </div>
</div>